### ISSUE TITLE
New Project Name

### ISSUE THREAD

**Issue by stephenlprice** [Tab-SE/tableau_langchain#31]
As the project has matured, the need for a new (non-stealth) name is clear. The current name of `langtab` is neither descriptive or clear. 

Current contributors are to vote on the new name for the project by choosing three options in descending order of preference and declaring them in the comments from the following list of choices:

- [ ] Tableau AI Query
- [ ] Tableau Chat Query
- [ ] Tableau Conversational Query
- [ ] Tableau NextGen Query
- [ ] Tableau AI Self-Service Analytics
- [ ] Tableau On-Demand Query
- [ ] Tableau Query Chain
- [ ] Tableau AI Wrapper
- [ ] Tableau AI Toolkit for Langchain
- [ ] Tableau AI Toolbox
- [ ] Tableau Chain Toolkit
- [x] tableau_ai_toolkit

 New names will be added to this list and votes will be declared in the comments. 

Name writing and voting will take place on our next meeting

**Comment by davidnguyen65536** [comment]
@stephenlprice a few other names:

1. **Tableau AI Pathfinder** - guide users through data exploration and discovery using AI
2. **Tableau AI Sage** - offer wise and data-driven guidance using AI
3. **Tableau AI Navigator** - steer users through the complexities of data analysis using AI
4. **Tableau AI Compass** - guide users towards meaningful insights using AI
5. **Tableau AI Luminary** - illuminate the path to data-driven decision using AI
